"""empty message

Revision ID: 3ce6d73ab45
Revises: 7d51298850d
Create Date: 2015-11-22 23:18:49.377574

"""

# revision identifiers, used by Alembic.
revision = '3ce6d73ab45'
down_revision = '7d51298850d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'date')
    ### end Alembic commands ###
